### ISSUE TITLE
Looking for old interface

### ISSUE THREAD

**Issue by bproffitt** [chaoss/prospector#2]
This might be a longshot, but I was trying to find the original set of displayed metrics  that was on the Prospector site. Not being a JavaScript developer, it's hard for me to find. A pointer to the components or the master page layout would be very helpful.

**Comment by jgbarah** [comment]
There is a live demo of Prospector online, at http://prospector.bitergia.net.

Can you find there what you need, or maybe are you looking for something else?

**Comment by sduenas** [comment]
@bproffitt are you looking for this ?

https://github.com/chaoss/prospector/blob/080acfda4c1164d70712bff71cef10ea3b1d80c3/wsgi/healthmeter/hmeter_frontend/fixtures/initial_metrics.json

**Comment by bproffitt** [comment]
Thanks! Found what I needed there!
